---
- name: Create CA
  hosts: localhost
  vars:
      certs_dir: "{{ playbook_dir }}/my_certs"
      country: "PL"
      common_name: "My Awesome CA"
      organization_name: "wiaderko"
  tasks:
    - name: create folders
      file:
        path: "{{ item }}"
        state: directory
      loop: 
        - "{{ certs_dir }}"
        - "{{ certs_dir }}/ca"
    - name: create CA key
      openssl_privatekey:
        path: "{{ certs_dir }}/ca/ca.key"
      register: ca_key
    - name: create the CA CSR
      openssl_csr:
        path: "{{ certs_dir }}/ca/ca.csr"
        privatekey_path: "{{ ca_key.filename }}"
        country_name: "{{ country }}"
        common_name: "{{ common_name }}"
        organization_name: "{{ organization_name }}"
        basic_constraints: ["CA:TRUE"]
      register: ca_csr
    - name: sign the CA CSR
      openssl_certificate:
        path: "{{ certs_dir }}/ca/ca.crt"
        csr_path: "{{ ca_csr.filename }}"
        privatekey_path: "{{ ca_key.filename }}"
        provider: selfsigned
      register: ca_crt
    - name: create PKCS file
      openssl_pkcs12:
        action: export
        path: "{{ certs_dir }}/ca/ca.p12"
        friendly_name: "{{ common_name }}"
        privatekey_path: "{{ ca_key.filename }}"
        certificate_path: "{{ certs_dir }}/ca/ca.crt"
        state: present
...

